name: mapbox_maps_flutter
description: A Flutter plugin for integrating Mapbox Maps SDK v10 in Android/iOS application.
version: 0.4.1
homepage: https://github.com/mapbox/mapbox-maps-flutter

# FIXME
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.5
  turf: ^0.0.7
  typed_data: ^1.3.0
  plugin_platform_interface: ^2.0.0
  mapbox_maps_flutter_platform_interface: 
    path: ./mapbox_maps_flutter_platform_interface
  mapbox_maps_flutter_web:
    path: ./mapbox_maps_flutter_web

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  pigeon: 3.2.3

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.maps.mapbox_maps
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web: 
        default_package: mapbox_maps_flutter_web

