name: mapbox_maps
description: Mapbox Maps Flutter Plugin for Mapbox Maps SDK v10.
version: 0.2.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.5
  turf: ^0.0.7
  typed_data: ^1.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  pigeon: 3.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.maps.mapbox_maps
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
