name: _
publish_to: none
environment:
  sdk: ">=3.6.0 <4.0.0"
workspace:
  - mapbox_maps_flutter_mobile
  - mapbox_maps_flutter_interface
  - mapbox_maps_flutter_web
  - mapbox_maps_flutter_v3
  - mapbox_maps_flutter_web/example
  - mapbox_maps_flutter_mobile/example
  - mapbox_maps_flutter_v3/example

dependencies:
  mapbox_maps_flutter: 
    path: mapbox_maps_flutter_mobile
  mapbox_maps_flutter_interface:
    path: mapbox_maps_flutter_interface
  mapbox_maps_flutter_web:
    path: mapbox_maps_flutter_web
  mapbox_maps_flutter_v3:
    path: mapbox_maps_flutter_v3