name: mapbox_maps_flutter
description: A Flutter plugin for integrating Mapbox Maps SDK v10 in Android/iOS application.
version: 0.5.1
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.5
  turf: ^0.0.7
  typed_data: ^1.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  pigeon:
    git:
      url: https://github.com/evil159/packages.git
      ref: 53718b121f385905a7baa1531f771d24bbb25a1d
      path: packages/pigeon


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.maps.mapbox_maps
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
