name: mapbox_maps_flutter_mobile
description: Interactive, thoroughly customizable maps powered by Mapbox Maps mobile SDKs.
version: 1.0.0
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.3"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.5
  typed_data: ^1.3.0
  meta: ^1.9.1
  mapbox_maps_flutter_interface: any

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: mapbox_maps_flutter_interface
    platforms:
      android:
        package: com.mapbox.maps.mapbox_maps
        pluginClass: MapboxMapsPlugin
        dartPluginClass: MapboxMapsFlutterMobile
      ios:
        pluginClass: MapboxMapsPlugin
        dartPluginClass: MapboxMapsFlutterMobile
